'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Navigation from '@/components/Navigation';
import { Search, ArrowLeft, Upload, CheckCircle, XCircle, AlertCircle, ExternalLink, Download } from 'lucide-react';
import { verifyByDocument, verifyByIpfsCid } from '@/services/verificationService';
import { getDegreeTypeName } from '@/lib/contracts';
import toast from 'react-hot-toast';

export default function VerifierPage() {
  const router = useRouter();
  const [verificationMethod, setVerificationMethod] = useState('document');
  const [verificationResult, setVerificationResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [ipfsCid, setIpfsCid] = useState('');
  const [selectedFile, setSelectedFile] = useState(null);

  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (file && file.type === 'application/pdf') {
      setSelectedFile(file);
      setVerificationResult(null);
    } else {
      toast.error('Please select a PDF file');
      e.target.value = '';
    }
  };

  const handleVerifyByDocument = async () => {
    if (!selectedFile) {
      toast.error('Please select a document first');
      return;
    }

    setLoading(true);
    const toastId = toast.loading('Verifying credential...');

    try {
      const result = await verifyByDocument(selectedFile);
      setVerificationResult(result);
      
      if (result.valid) {
        toast.success('Credential verified successfully!', { id: toastId });
      } else {
        toast.error(result.message || 'Credential not found or invalid', { id: toastId });
      }
    } catch (error) {
      console.error('Verification error:', error);
      toast.error('Failed to verify credential', { id: toastId });
      setVerificationResult({ valid: false, message: 'Verification failed' });
    } finally {
      setLoading(false);
    }
  };

  const handleVerifyByCid = async () => {
    if (!ipfsCid.trim()) {
      toast.error('Please enter an IPFS CID');
      return;
    }

    setLoading(true);
    const toastId = toast.loading('Verifying credential...');

    try {
      const result = await verifyByIpfsCid(ipfsCid);
      setVerificationResult(result);
      
      if (result.valid) {
        toast.success('Credential verified successfully!', { id: toastId });
      } else {
        toast.error(result.message || 'Credential not found or invalid', { id: toastId });
      }
    } catch (error) {
      console.error('Verification error:', error);
      toast.error('Failed to verify credential', { id: toastId });
      setVerificationResult({ valid: false, message: 'Verification failed' });
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!verificationResult || !verificationResult.valid) return;

    const report = `
CREDENTIAL VERIFICATION REPORT
==============================

Verification Status: VALID
Verification Date: ${new Date().toLocaleString()}

CREDENTIAL DETAILS
------------------
Credential Type: ${getDegreeTypeName(verificationResult.credential.credentialType)}
Graduation Year: ${verificationResult.credential.graduationYear}
Issue Date: ${new Date(verificationResult.credential.createdAt).toLocaleDateString()}

INSTITUTION
-----------
Institution Address: ${verificationResult.credential.institutionAddress}

STUDENT
-------
Student Address: ${verificationResult.credential.studentAddress}

BLOCKCHAIN DATA
---------------
Document Hash: ${verificationResult.credential.documentHash}
IPFS CID: ${verificationResult.credential.ipfsCid}
Transaction Hash: ${verificationResult.credential.transactionHash}
Block Number: ${verificationResult.credential.blockNumber}

VERIFICATION
------------
This credential has been verified on the Polygon blockchain.
The document hash matches the on-chain record.
Status: ${verificationResult.credential.status}

View on IPFS: ${verificationResult.credential.ipfsUrl || `${process.env.NEXT_PUBLIC_PINATA_GATEWAY}/ipfs/${verificationResult.credential.ipfsCid}`}
View Transaction: ${(() => { let base = process.env.NEXT_PUBLIC_EXPLORER_TX_URL || ''; if (!base) { const id = typeof window !== 'undefined' ? window?.ethereum?.chainId : undefined; switch (id) { case '0xaa36a7': base = 'https://sepolia.etherscan.io/tx/'; break; case '0x13882': base = 'https://amoy.polygonscan.com/tx/'; break; default: base = 'https://etherscan.io/tx/'; } } return `${base}${verificationResult.credential.transactionHash}`; })()}

==============================
Generated by CredChain Verification System
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `verification-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <Navigation />
      
      <main className="max-w-4xl mx-auto px-4 py-8">
        <button
          onClick={() => router.push('/')}
          className="text-blue-600 hover:text-blue-700 mb-6 flex items-center space-x-2 transition"
        >
          <ArrowLeft className="w-5 h-5" />
          <span>Back to Home</span>
        </button>

        <div className="bg-white rounded-2xl shadow-lg p-8">
          <div className="mb-8">
            <div className="flex items-center space-x-3 mb-2">
              <Search className="w-8 h-8 text-orange-600" />
              <h1 className="text-3xl font-bold text-gray-900">Verify Credentials</h1>
            </div>
            <p className="text-gray-600">Instantly verify the authenticity of academic transcripts</p>
          </div>

          {/* Verification Method Toggle */}
          <div className="flex space-x-4 mb-8">
            <button
              onClick={() => {
                setVerificationMethod('document');
                setVerificationResult(null);
              }}
              className={`flex-1 py-3 px-6 rounded-lg font-semibold transition ${
                verificationMethod === 'document'
                  ? 'bg-orange-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              Upload Document
            </button>
            <button
              onClick={() => {
                setVerificationMethod('cid');
                setVerificationResult(null);
              }}
              className={`flex-1 py-3 px-6 rounded-lg font-semibold transition ${
                verificationMethod === 'cid'
                  ? 'bg-orange-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              Enter IPFS CID
            </button>
          </div>

          {/* Document Upload Method */}
          {verificationMethod === 'document' && (
            <div className="space-y-6">
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-12 text-center hover:border-orange-500 transition cursor-pointer">
                <input
                  id="verifyFileInput"
                  type="file"
                  accept="application/pdf"
                  onChange={handleFileSelect}
                  className="hidden"
                />
                <label htmlFor="verifyFileInput" className="cursor-pointer">
                  <Upload className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                  <p className="text-lg text-gray-700 mb-2">
                    {selectedFile ? selectedFile.name : 'Upload Transcript PDF'}
                  </p>
                  <p className="text-sm text-gray-500">Click to upload or drag and drop</p>
                </label>
              </div>
              <button
                onClick={handleVerifyByDocument}
                disabled={loading || !selectedFile}
                className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700 transition font-semibold text-lg disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? 'Verifying...' : 'Verify Document'}
              </button>
            </div>
          )}

          {/* IPFS CID Method */}
          {verificationMethod === 'cid' && (
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">IPFS CID</label>
                <input
                  type="text"
                  value={ipfsCid}
                  onChange={(e) => setIpfsCid(e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent font-mono"
                  placeholder="QmXx1234..."
                />
              </div>
              <button
                onClick={handleVerifyByCid}
                disabled={loading || !ipfsCid.trim()}
                className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700 transition font-semibold text-lg disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? 'Verifying...' : 'Verify Credential'}
              </button>
            </div>
          )}

          {/* Verification Result */}
          {verificationResult && (
            <div className="mt-8 border-t pt-8">
              <div
                className={`rounded-xl p-6 ${
                  verificationResult.valid
                    ? 'bg-green-50 border-2 border-green-500'
                    : 'bg-red-50 border-2 border-red-500'
                }`}
              >
                <div className="flex items-center space-x-3 mb-4">
                  {verificationResult.valid ? (
                    <>
                      <CheckCircle className="w-8 h-8 text-green-600" />
                      <h3 className="text-2xl font-bold text-green-900">Credential Verified ✓</h3>
                    </>
                  ) : (
                    <>
                      <XCircle className="w-8 h-8 text-red-600" />
                      <h3 className="text-2xl font-bold text-red-900">Invalid Credential ✗</h3>
                    </>
                  )}
                </div>

                {verificationResult.valid && verificationResult.credential && (
                  <div className="space-y-3">
                    <div className="grid md:grid-cols-2 gap-4 mt-6">
                      <div className="bg-white rounded-lg p-4">
                        <p className="text-sm text-gray-600 mb-1">Issuing Institution</p>
                        <p className="font-bold text-gray-900 text-lg font-mono text-sm">
                          {verificationResult.credential.institutionAddress.slice(0, 10)}...
                          {verificationResult.credential.institutionAddress.slice(-8)}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4">
                        <p className="text-sm text-gray-600 mb-1">Credential Type</p>
                        <p className="font-bold text-gray-900 text-lg">
                          {getDegreeTypeName(verificationResult.credential.credentialType)}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4">
                        <p className="text-sm text-gray-600 mb-1">Graduation Year</p>
                        <p className="font-bold text-gray-900 text-lg">
                          {verificationResult.credential.graduationYear}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4">
                        <p className="text-sm text-gray-600 mb-1">Issue Date</p>
                        <p className="font-bold text-gray-900 text-lg">
                          {new Date(verificationResult.credential.createdAt).toLocaleDateString()}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4 md:col-span-2">
                        <p className="text-sm text-gray-600 mb-1">Student Wallet Address</p>
                        <p className="font-mono text-gray-900 text-sm">
                          {verificationResult.credential.studentAddress}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4 md:col-span-2">
                        <p className="text-sm text-gray-600 mb-1">IPFS CID</p>
                        <p className="font-mono text-sm text-gray-900">
                          {verificationResult.credential.ipfsCid}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-4 md:col-span-2">
                        <p className="text-sm text-gray-600 mb-1">Status</p>
                        <span
                          className={`inline-block px-3 py-1 rounded-full text-sm font-semibold ${
                            verificationResult.credential.status === 'Active'
                              ? 'bg-green-100 text-green-700'
                              : 'bg-red-100 text-red-700'
                          }`}
                        >
                          {verificationResult.credential.status}
                        </span>
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-3 mt-6">
                      <button
                        onClick={() => { const url = verificationResult.credential.ipfsUrl || `${process.env.NEXT_PUBLIC_PINATA_GATEWAY}/ipfs/${verificationResult.credential.ipfsCid}`; window.open(url, '_blank'); }}
                        className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition flex items-center space-x-2"
                      >
                        <ExternalLink className="w-4 h-4" />
                        <span>View Document on IPFS</span>
                      </button>
                      <button
                        onClick={handleDownloadReport}
                        className="bg-white text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-100 transition border border-gray-300 flex items-center space-x-2"
                      >
                        <Download className="w-4 h-4" />
                        <span>Download Report</span>
                      </button>
                      {verificationResult.credential.transactionHash && (
                        <button
                          onClick={() => {
                            const href = (() => { let base = process.env.NEXT_PUBLIC_ETHERSCAN_URL || ''; if (!base) { const id = typeof window !== 'undefined' ? window?.ethereum?.chainId : undefined; switch (id) { case '0xaa36a7': base = 'https://sepolia.etherscan.io/tx/'; break; case '0x13882': base = 'https://amoy.polygonscan.com/tx/'; break; default: base = 'https://etherscan.io/tx/'; } } return `${base}${verificationResult.credential.transactionHash}`; })();
                            window.open(href, '_blank');
                          }}
                          className="bg-white text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-100 transition border border-gray-300 flex items-center space-x-2"
                        >
                          <ExternalLink className="w-4 h-4" />
                          <span>View Transaction</span>
                        </button>
                      )}
                    </div>
                  </div>
                )}

                {!verificationResult.valid && (
                  <div className="mt-4 bg-white rounded-lg p-4">
                    <div className="flex items-start space-x-3">
                      <AlertCircle className="w-5 h-5 text-red-600 mt-0.5" />
                      <div>
                        <p className="font-semibold text-gray-900">This credential could not be verified</p>
                        <p className="text-gray-600 mt-1">
                          {verificationResult.message ||
                            'The document hash does not match any credential on the blockchain, or the credential has been revoked.'}
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Info Section */}
          <div className="mt-8 bg-blue-50 rounded-lg p-6 border border-blue-200">
            <div className="flex items-start space-x-3">
              <AlertCircle className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">How Verification Works</h4>
                <ul className="text-sm text-gray-700 space-y-1">
                  <li>• Upload the transcript PDF or enter the IPFS CID provided by the student</li>
                  <li>• The system calculates the document hash and checks it against the blockchain</li>
                  <li>• Verification is instant and cryptographically secure</li>
                  <li>• No login required - verification is publicly accessible</li>
                  <li>• All credential data is stored on Ethereum Sepolia blockchain for transparency</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}