'use client';

import { useState } from 'react';
import { Search, Upload, CheckCircle, XCircle, AlertCircle, ExternalLink, Download, FileText } from 'lucide-react';
import { verifyByDocument, verifyByIpfsCid } from '@/services/verificationService';
import { credentialTypes } from '@/lib/utils';
import toast from 'react-hot-toast';

export default function VerifierPortal() {
  const [verificationMethod, setVerificationMethod] = useState('document');
  const [verificationResult, setVerificationResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [ipfsCid, setIpfsCid] = useState('');
  const [selectedFile, setSelectedFile] = useState(null);
  const [dragActive, setDragActive] = useState(false);

  // Handle drag events
  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  // Handle drop event
  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileSelection(e.dataTransfer.files[0]);
    }
  };

  // Handle file selection
  const handleFileSelection = (file) => {
    if (file && file.type === 'application/pdf') {
      setSelectedFile(file);
      setVerificationResult(null);
      toast.success('File selected: ' + file.name);
    } else {
      toast.error('Please select a PDF file');
    }
  };

  // Handle file input change
  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (file) {
      handleFileSelection(file);
    }
  };

  // Verify by document upload
  const handleVerifyByDocument = async () => {
    if (!selectedFile) {
      toast.error('Please select a document first');
      return;
    }

    setLoading(true);
    const toastId = toast.loading('Verifying credential...');

    try {
      const result = await verifyByDocument(selectedFile);
      setVerificationResult(result);
      
      if (result.valid) {
        toast.success('✓ Credential verified successfully!', { id: toastId });
      } else {
        toast.error('✗ ' + (result.message || 'Credential not found or invalid'), { id: toastId });
      }
    } catch (error) {
      console.error('Verification error:', error);
      toast.error('Failed to verify credential', { id: toastId });
      setVerificationResult({ valid: false, message: 'Verification failed. Please try again.' });
    } finally {
      setLoading(false);
    }
  };

  // Verify by IPFS CID
  const handleVerifyByCid = async () => {
    if (!ipfsCid.trim()) {
      toast.error('Please enter an IPFS CID');
      return;
    }

    setLoading(true);
    const toastId = toast.loading('Verifying credential...');

    try {
      const result = await verifyByIpfsCid(ipfsCid.trim());
      setVerificationResult(result);
      
      if (result.valid) {
        toast.success('✓ Credential verified successfully!', { id: toastId });
      } else {
        toast.error('✗ ' + (result.message || 'Credential not found or invalid'), { id: toastId });
      }
    } catch (error) {
      console.error('Verification error:', error);
      toast.error('Failed to verify credential', { id: toastId });
      setVerificationResult({ valid: false, message: 'Verification failed. Please try again.' });
    } finally {
      setLoading(false);
    }
  };

  // Download verification report
  const handleDownloadReport = () => {
    if (!verificationResult || !verificationResult.valid) return;

    const cred = verificationResult.credential;
    const report = `
╔════════════════════════════════════════════════════════════════╗
║          CREDENTIAL VERIFICATION REPORT                        ║
╚════════════════════════════════════════════════════════════════╝

Verification Status: ✓ VALID
Verification Date: ${new Date().toLocaleString()}
Report Generated By: CredChain Verification System

════════════════════════════════════════════════════════════════

CREDENTIAL DETAILS
------------------
Credential Type: ${credentialTypes[cred.credentialType]}
Graduation Year: ${cred.graduationYear}
Issue Date: ${new Date(cred.createdAt).toLocaleDateString('en-US', { 
  year: 'numeric', 
  month: 'long', 
  day: 'numeric' 
})}
Current Status: ${cred.status}

ISSUING INSTITUTION
-------------------
Institution Wallet: ${cred.institutionAddress}

STUDENT INFORMATION
-------------------
Student Wallet: ${cred.studentAddress}

BLOCKCHAIN VERIFICATION
-----------------------
Document Hash: ${cred.documentHash}
IPFS CID: ${cred.ipfsCid}
Transaction Hash: ${cred.transactionHash}
Block Number: ${cred.blockNumber}

VERIFICATION DETAILS
--------------------
✓ Document hash matches blockchain record
✓ Credential has not been revoked
✓ Issuing institution is verified
✓ Cryptographic verification successful

════════════════════════════════════════════════════════════════

EXTERNAL LINKS
--------------
View Document on IPFS:
${cred.ipfsUrl}

View Transaction on PolygonScan:
https://mumbai.polygonscan.com/tx/${cred.transactionHash}

════════════════════════════════════════════════════════════════

IMPORTANT NOTICE
This verification report confirms the authenticity of the credential
on the blockchain. Any modification to the original document will
result in a different hash and fail verification.

Report ID: ${Date.now()}
Generated: ${new Date().toISOString()}

════════════════════════════════════════════════════════════════
CredChain - Decentralized Transcript Verification
Powered by Polygon Blockchain & IPFS
════════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `credential-verification-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Verification report downloaded successfully');
  };

  // Reset verification
  const resetVerification = () => {
    setVerificationResult(null);
    setSelectedFile(null);
    setIpfsCid('');
    const fileInput = document.getElementById('verifyFileInput');
    if (fileInput) fileInput.value = '';
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center space-x-3 mb-2">
          <Search className="w-8 h-8 text-orange-600" />
          <h1 className="text-3xl font-bold text-gray-900">Verify Credentials</h1>
        </div>
        <p className="text-gray-600">Instantly verify the authenticity of academic transcripts</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm p-8">
        {/* Verification Method Toggle */}
        <div className="flex space-x-4 mb-8">
          <button
            onClick={() => {
              setVerificationMethod('document');
              resetVerification();
            }}
            className={`flex-1 py-3 px-6 rounded-lg font-semibold transition ${
              verificationMethod === 'document'
                ? 'bg-orange-600 text-white shadow-md'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            <Upload className="w-5 h-5 inline-block mr-2" />
            Upload Document
          </button>
          <button
            onClick={() => {
              setVerificationMethod('cid');
              resetVerification();
            }}
            className={`flex-1 py-3 px-6 rounded-lg font-semibold transition ${
              verificationMethod === 'cid'
                ? 'bg-orange-600 text-white shadow-md'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            <FileText className="w-5 h-5 inline-block mr-2" />
            Enter IPFS CID
          </button>
        </div>

        {/* Document Upload Method */}
        {verificationMethod === 'document' && (
          <div className="space-y-6">
            <div
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={handleDrop}
              className={`border-2 border-dashed rounded-lg p-12 text-center transition cursor-pointer ${
                dragActive
                  ? 'border-orange-500 bg-orange-50'
                  : selectedFile
                  ? 'border-green-500 bg-green-50'
                  : 'border-gray-300 hover:border-orange-400'
              }`}
            >
              <input
                id="verifyFileInput"
                type="file"
                accept="application/pdf"
                onChange={handleFileSelect}
                className="hidden"
              />
              <label htmlFor="verifyFileInput" className="cursor-pointer">
                {selectedFile ? (
                  <>
                    <CheckCircle className="w-16 h-16 text-green-600 mx-auto mb-4" />
                    <p className="text-lg text-green-700 font-semibold mb-2">
                      {selectedFile.name}
                    </p>
                    <p className="text-sm text-gray-600">
                      File size: {(selectedFile.size / 1024).toFixed(2)} KB
                    </p>
                    <p className="text-sm text-gray-500 mt-2">Click to select a different file</p>
                  </>
                ) : (
                  <>
                    <Upload className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                    <p className="text-lg text-gray-700 mb-2">
                      Upload Transcript PDF
                    </p>
                    <p className="text-sm text-gray-500">
                      Click to upload or drag and drop
                    </p>
                    <p className="text-xs text-gray-400 mt-1">PDF files only, max 10MB</p>
                  </>
                )}
              </label>
            </div>
            <button
              onClick={handleVerifyByDocument}
              disabled={loading || !selectedFile}
              className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700 transition font-semibold text-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
            >
              {loading ? (
                <>
                  <div className="loading-spinner w-5 h-5 border-2"></div>
                  <span>Verifying...</span>
                </>
              ) : (
                <>
                  <Search className="w-5 h-5" />
                  <span>Verify Document</span>
                </>
              )}
            </button>
          </div>
        )}

        {/* IPFS CID Method */}
        {verificationMethod === 'cid' && (
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                IPFS CID (Content Identifier)
              </label>
              <input
                type="text"
                value={ipfsCid}
                onChange={(e) => setIpfsCid(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent font-mono text-sm"
                placeholder="Example: QmXx1234abcd5678..."
              />
              <p className="text-xs text-gray-500 mt-2">
                Enter the IPFS Content Identifier provided by the student
              </p>
            </div>
            <button
              onClick={handleVerifyByCid}
              disabled={loading || !ipfsCid.trim()}
              className="w-full bg-orange-600 text-white py-3 rounded-lg hover:bg-orange-700 transition font-semibold text-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
            >
              {loading ? (
                <>
                  <div className="loading-spinner w-5 h-5 border-2"></div>
                  <span>Verifying...</span>
                </>
              ) : (
                <>
                  <Search className="w-5 h-5" />
                  <span>Verify Credential</span>
                </>
              )}
            </button>
          </div>
        )}

        {/* Verification Result */}
        {verificationResult && (
          <div className="mt-8 pt-8 border-t border-gray-200 animate-slide-up">
            <div
              className={`rounded-xl p-6 ${
                verificationResult.valid
                  ? 'bg-green-50 border-2 border-green-500'
                  : 'bg-red-50 border-2 border-red-500'
              }`}
            >
              <div className="flex items-center space-x-3 mb-6">
                {verificationResult.valid ? (
                  <>
                    <div className="bg-green-600 rounded-full p-2">
                      <CheckCircle className="w-10 h-10 text-white" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold text-green-900">Credential Verified ✓</h3>
                      <p className="text-green-700 text-sm">This credential is authentic and valid</p>
                    </div>
                  </>
                ) : (
                  <>
                    <div className="bg-red-600 rounded-full p-2">
                      <XCircle className="w-10 h-10 text-white" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold text-red-900">Invalid Credential ✗</h3>
                      <p className="text-red-700 text-sm">This credential could not be verified</p>
                    </div>
                  </>
                )}
              </div>

              {verificationResult.valid && verificationResult.credential && (
                <div className="space-y-4">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="bg-white rounded-lg p-4 shadow-sm">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Issuing Institution</p>
                      <p className="font-bold text-gray-900 font-mono text-sm">
                        {verificationResult.credential.institutionAddress.slice(0, 10)}...
                        {verificationResult.credential.institutionAddress.slice(-8)}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Credential Type</p>
                      <p className="font-bold text-gray-900 text-lg">
                        {credentialTypes[verificationResult.credential.credentialType]}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Graduation Year</p>
                      <p className="font-bold text-gray-900 text-lg">
                        {verificationResult.credential.graduationYear}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Issue Date</p>
                      <p className="font-bold text-gray-900 text-lg">
                        {new Date(verificationResult.credential.createdAt).toLocaleDateString()}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm md:col-span-2">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Student Wallet Address</p>
                      <p className="font-mono text-gray-900 text-sm break-all">
                        {verificationResult.credential.studentAddress}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm md:col-span-2">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">IPFS CID</p>
                      <p className="font-mono text-sm text-gray-900 break-all">
                        {verificationResult.credential.ipfsCid}
                      </p>
                    </div>
                    <div className="bg-white rounded-lg p-4 shadow-sm md:col-span-2">
                      <p className="text-xs text-gray-600 mb-1 uppercase font-semibold">Status</p>
                      <span
                        className={`inline-block px-3 py-1 rounded-full text-sm font-semibold ${
                          verificationResult.credential.status === 'Active'
                            ? 'bg-green-100 text-green-700'
                            : 'bg-red-100 text-red-700'
                        }`}
                      >
                        {verificationResult.credential.status}
                      </span>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-3 pt-4">
                    <button
                      onClick={() => window.open(verificationResult.credential.ipfsUrl, '_blank')}
                      className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition flex items-center space-x-2"
                    >
                      <ExternalLink className="w-4 h-4" />
                      <span>View Document on IPFS</span>
                    </button>
                    <button
                      onClick={handleDownloadReport}
                      className="bg-white text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-100 transition border border-gray-300 flex items-center space-x-2"
                    >
                      <Download className="w-4 h-4" />
                      <span>Download Report</span>
                    </button>
                    {verificationResult.credential.transactionHash && (
                      <button
                        onClick={() =>
                          window.open(
                            `https://mumbai.polygonscan.com/tx/${verificationResult.credential.transactionHash}`,
                            '_blank'
                          )
                        }
                        className="bg-white text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-100 transition border border-gray-300 flex items-center space-x-2"
                      >
                        <ExternalLink className="w-4 h-4" />
                        <span>View on PolygonScan</span>
                      </button>
                    )}
                  </div>

                  <button
                    onClick={resetVerification}
                    className="w-full mt-4 bg-gray-100 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-200 transition"
                  >
                    Verify Another Credential
                  </button>
                </div>
              )}

              {!verificationResult.valid && (
                <div className="mt-4 bg-white rounded-lg p-4">
                  <div className="flex items-start space-x-3">
                    <AlertCircle className="w-5 h-5 text-red-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="font-semibold text-gray-900 mb-2">Verification Failed</p>
                      <p className="text-gray-600 mb-3">
                        {verificationResult.message ||
                          'The document could not be verified. This may mean:'}
                      </p>
                      <ul className="text-sm text-gray-600 space-y-1">
                        <li>• The document has been modified or tampered with</li>
                        <li>• The credential was never issued on the blockchain</li>
                        <li>• The credential has been revoked by the institution</li>
                        <li>• The IPFS CID is incorrect or invalid</li>
                      </ul>
                      <button
                        onClick={resetVerification}
                        className="mt-4 text-sm text-blue-600 hover:text-blue-700 font-semibold"
                      >
                        Try verifying another credential →
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Info Section */}
      <div className="bg-blue-50 rounded-xl p-6 border border-blue-200">
        <div className="flex items-start space-x-3">
          <AlertCircle className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
          <div>
            <h4 className="font-semibold text-gray-900 mb-2">How Verification Works</h4>
            <ul className="text-sm text-gray-700 space-y-2">
              <li>• <strong>Upload Document:</strong> Upload the PDF transcript you received from the student</li>
              <li>• <strong>Or Enter CID:</strong> Use the IPFS Content Identifier shared by the student</li>
              <li>• <strong>Instant Check:</strong> System calculates document hash and verifies against blockchain</li>
              <li>• <strong>Cryptographic Proof:</strong> Verification uses SHA-256 hashing for security</li>
              <li>• <strong>No Login Required:</strong> Public verification accessible to everyone</li>
              <li>• <strong>Tamper-Proof:</strong> Any modification to the document will fail verification</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}